#pragma once
#ifndef _FSFILTER_WORKITEMS_H
#define _FSFILTER_WORKITEMS_H

#include "Common.h"
#include "..\FsCore\Ecp.h"

typedef enum _WORKITEM_PREORPOST
{
	WORKITEM_PREORPOST_NONE = 0,

	WORKITEM_PREORPOST_PRECALLBACK,
	WORKITEM_PREORPOST_POSTCALLBACK,

	WORKITEM_PREORPOST_MAX
}
WORKITEM_PREORPOST;

typedef struct _FSFILTER_WORKITEMCTX_CREATEDIR
{
	PFSFLT_REPARSE_INFO_ECP_CONTEXT pEcpCtx;
	WORKITEM_PREORPOST PreOrPost;
}
FSFILTER_WORKITEMCTX_CREATEDIR, *PFSFILTER_WORKITEMCTX_CREATEDIR;

typedef struct _FSFILTER_WORKITEMCTX_SETSECURITY
{
	WORKITEM_PREORPOST PreOrPost;
}
FSFILTER_WORKITEMCTX_SETSECURITY, *PFSFILTER_WORKITEMCTX_SETSECURITY;

VOID WorkItem_CreateDir(
	_In_ PFLT_DEFERRED_IO_WORKITEM FltWorkItem,
	_In_ PFLT_CALLBACK_DATA CallbackData,
	_In_opt_ PVOID Context
);

VOID WorkItem_SetSecurity(
	_In_ PFLT_DEFERRED_IO_WORKITEM FltWorkItem,
	_In_ PFLT_CALLBACK_DATA CallbackData,
	_In_opt_ PVOID Context
);

#endif // !_FSFILTER_WORKITEMS_H
